---
title: "flat_check_data.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(stringr)

# test<-names(nyc_squirrels_act) %in% c("primary_fur_color","long","lat")
# 
# length(test[test=="TRUE"])
  

```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# check_plus_in_primary_fur_color

```{r function-check_plus_in_primary_fur_color}

#' Check the values of primary fur color
#'
#' @param primary_fur_color Character. A vector with the primary fur color.
#' @return a vector of logicals
#' @importFrom stringr str_detect
#' @export
check_plus_in_primary_fur_color <- function(primary_fur_color) {
  
  if (isFALSE(class(primary_fur_color)=="character")){
    stop("Your input is not a character.")
  }
  
  colors_are_ok <- !str_detect(string = primary_fur_color, pattern = "\\+")
  return(colors_are_ok)
}

```

```{r examples-check_plus_in_primary_fur_color}

check_plus_in_primary_fur_color(c("Black", "Black+Cinnamon", "Cinnamon", NA))

```

```{r tests-check_plus_in_primary_fur_color}
test_that("check_plus_in_primary_fur_color works", {
  expect_error(check_plus_in_primary_fur_color(iris),
               regexp="Your input is not a character.")
  
  expect_equal(check_plus_in_primary_fur_color(c("Black", "Black+Cinnamon", "Cinnamon", NA)),c(TRUE,FALSE,TRUE,NA))

})
```


# check_coordinates

```{r function-check_coordinates}

#' Checks if the coordinates are in Central Park
#'
#' @param latitude numeric. A vector with the latitude.
#' @param longitude numeric. A vector with the longitude.
#' @return a vector of logicals
#'
#' @export
check_coordinates <- function(latitude, longitude) {
  if (isFALSE(is.numeric(latitude)) | isFALSE(is.numeric(longitude))) {
    stop("latitude and longitude should be numeric")
  }

  coordinates_are_ok <-
    latitude > 40.76400 & latitude < 40.80100 &
      longitude > -73.98300 & longitude < -73.94735

  return(coordinates_are_ok)
}

```

```{r examples-check_coordinates}

both_valid_latitude <- c(40.766, 40.799)
both_valid_longitude <- c(-73.96, -73.95)
both_invalid_latitude <- c(30, 32)
both_invalid_longitude <- c(-100, -99)
one_invalid_latitude <- c(40.766, 50)
one_invalid_longitude <- c(-73.95, -100)

check_coordinates(
  latitude = both_valid_latitude,
  longitude = both_valid_longitude
)

check_coordinates(
  latitude = both_invalid_latitude,
  longitude = both_invalid_longitude
)

check_coordinates(
  latitude = one_invalid_latitude,
  longitude = one_invalid_longitude
)
```

```{r tests-check_coordinates}

both_valid_latitude <- c(40.766, 40.799)
both_valid_longitude <- c(-73.96, -73.95)
both_invalid_latitude <- c(30, 32)
both_invalid_longitude <- c(-100, -99)
one_invalid_latitude <- c(40.766, 50)
one_invalid_longitude <- c(-73.95, -100)

test_that("check_coordinates  works", {
  expect_equal(check_coordinates(
  latitude = both_valid_latitude,
  longitude = both_valid_longitude
),c(TRUE,TRUE))
  expect_equal(check_coordinates(
  latitude = both_invalid_latitude,
  longitude = both_invalid_longitude
),c(FALSE,FALSE))
  expect_equal(check_coordinates(
  latitude = one_invalid_latitude,
  longitude = one_invalid_longitude
),c(TRUE,FALSE))
  expect_error(check_coordinates(
  latitude = c("a","b"),
  longitude = both_valid_longitude
))
expect_error(check_coordinates(
  latitude = both_valid_latitude,
  longitude = c("a","b")
))
})
```

# check_presence_of_required_columns
    
```{r function-check_presence_of_required_columns}
#' Title check_presence_of_required_columns
#' 
#' Description Cette fonction compte si les 3 variables nécessaires pour l'analyse sont présentes dans la base de données
#' 
#' @param data data.frame 
#'
#' @return numerical. Il donne le nombre de variables présentes parmi les variables nécessaires
#' 
#' @export
check_presence_of_required_columns <- function(data){
  
  if (isFALSE(any(class(data) %in% c("data.frame")))){
    stop("Your input is not a data.frame")
  }
  
    temp<-names(data) %in% c("primary_fur_color","long","lat")
    
    check<-length(temp[temp=="TRUE"])
    if (check==3){
      message("Toutes les variables sont présentes")
    } else{
      manque = 3 - check
      message(paste0("Il manque ", manque, " variables."))
    }
  return(check)
}
```
  
```{r example-check_presence_of_required_columns}
check_presence_of_required_columns(mtcars)
check_presence_of_required_columns(iris)
check_presence_of_required_columns(data_demo_squirrels)
```
  
```{r tests-check_presence_of_required_columns}

data("data_demo_squirrels")
test_that("check_presence_of_required_columns works", {
  expect_true(inherits(check_presence_of_required_columns, "function"))
  expect_equal(check_presence_of_required_columns(mtcars),0)
  expect_equal(check_presence_of_required_columns(iris),0)
  expect_equal(check_presence_of_required_columns(data_demo_squirrels),3)
  expect_error(check_presence_of_required_columns(2))
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_check_data.Rmd", vignette_name = "Go further",overwrite = TRUE,open_vignette = FALSE)
```

