# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function"))
  expect_error(save_as_csv(2,"test.csv"))
  expect_error(save_as_csv(data_demo_squirrels,"test.xlsx"))
})
