# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand


data("data_demo_squirrels")
test_that("check_presence_of_required_columns works", {
  expect_true(inherits(check_presence_of_required_columns, "function"))
  expect_equal(check_presence_of_required_columns(mtcars),0)
  expect_equal(check_presence_of_required_columns(iris),0)
  expect_equal(check_presence_of_required_columns(data_demo_squirrels),3)
  expect_error(check_presence_of_required_columns(2))
})
