# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_plus_in_primary_fur_color works", {
  expect_error(check_plus_in_primary_fur_color(iris),
               regexp="Your input is not a character.")
  
  expect_equal(check_plus_in_primary_fur_color(c("Black", "Black+Cinnamon", "Cinnamon", NA)),c(TRUE,FALSE,TRUE,NA))

})
