# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Title check_presence_of_required_columns
#' 
#' Description Cette fonction compte si les 3 variables nécessaires pour l'analyse sont présentes dans la base de données
#' 
#' @return Il donne le nombre de variables présentes parmi les variables nécessaires
#' 
#' @export
#' @examples
#' check_presence_of_required_columns(mtcars)
#' check_presence_of_required_columns(iris)
#' check_presence_of_required_columns(data_demo_squirrels)
check_presence_of_required_columns <- function(data){
  
  if (isFALSE(any(class(data) %in% c("data.frame")))){
    stop("Your input is not a data.frame")
  }
  
    temp<-names(data) %in% c("primary_fur_color","long","lat")
    
    check<-length(temp[temp=="TRUE"])
    if (check==3){
      message("Toutes les variables sont présentes")
    } else{
      manque = 3 - check
      message(paste0("Il manque ", manque, " variables."))
    }
  return(check)
}
