# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' Exportations de données
#' 
#' Cette fonction permet d'exporter les données en format csv
#' 
#' @return Le chemin ou se trouve le fichier créé
#' 
#' @importFrom utils write2.csv 
#' @importFrom glue glue_collapse
#' 
#' @export
#'  
#' @examples
#' data("data_demo_squirrels")
#' save_as_csv(data_demo_squirrels,"data.csv")

save_as_csv <- function(df,chemin){
  problem<-NULL
  if (isFALSE(inherits(df,"data.frame"))){
    problem$df<-"df is not a data.frame"
  } 
  if (isFALSE(tools::file_ext(chemin)%in% "csv")){
    problem$chemin<-"chemin is not a correct path"
  } 
  
  if (length(problem)!=0){
    stop(glue_collapse(problem, "\n"))
  }

  write.csv2(data_test,file="data_test.csv")

  return(chemin)
  
}
