# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' Exportations de données
#' 
#' Cette fonction permet d'exporter les donnees en format csv
#'
#' @param chemin Donner le chemin ou le fichier sera enregistre
#' @param df data.frame
#'
#' @return Le chemin ou se trouve le fichier
#' 
#' @importFrom utils write.csv2 
#' @importFrom glue glue_collapse 
#' 
#' @export
#'  
#' @examples
#'
#' mon_dossier_temp_aleatoire <- tempfile(pattern = "toto")
#' dir.create(mon_dossier_temp_aleatoire) # crée le dossier temporaire
#' mon_chemin <-(file.path(mon_dossier_temp_aleatoire, "monfichier.csv"))
#'
#' data("data_demo_squirrels")
#' save_as_csv(data_demo_squirrels,mon_chemin)
#' unlink(mon_chemin)

save_as_csv <- function(df,chemin){
  problem<-NULL
  if (isFALSE(inherits(df,"data.frame"))){
    problem$df<-"df is not a data.frame"
  } 
  if (isFALSE(tools::file_ext(chemin)%in% "csv")){
    problem$chemin<-"chemin is not a correct path"
  } 
  
  if (length(problem)!=0){
    stop(glue_collapse(problem, "\n"))
  }

  write.csv2(df,file=chemin)

  return(chemin)
  
}
